Do increment #13
goshansmails/shortener pull request #13
Opened 2024-02-13 20:08 UTC by goshansmails

2024-02-16 00:47 UTC, Nikscorp requested changes
Оставил замечания в комментариях к pr

2024-02-16 00:47 UTC, Nikscorp commented on internal/server/ping.go
> +		s.logger.Error("ping fail", zap.String("error", err.Error()))
zap.Error

2024-02-16 00:47 UTC, Nikscorp commented on internal/server/shorten_batch.go
> +		id, err := s.store.GetOrGenerateID(item.OriginalURL)
контекст не прокидывается

2024-02-16 00:47 UTC, Nikscorp commented on internal/server/shorten_batch.go
> +	for _, item := range reqData.Items {
вообще смысл батчевого метода в том, что мы оптимизируем запросы, а не делаем их по-одному). То есть в БД делаем не N запросов (где N длина items), а в идеале 1 (с поправкой на ограничения размера батча).

Это не совсем тривиально, так что поправь только если останется достаточно времени.

2024-02-16 00:47 UTC, Nikscorp commented on internal/server/shorten_url.go
> +	id, err := s.store.GetOrGenerateID(longURL)
контекст не прикидывается, актуально для всех методологов стора. Получается при закрытии реквеста ты автоматом не завершишь все запросы к БД и сервер будет продолжать бесполезную работу

2024-02-16 00:47 UTC, Nikscorp commented on internal/store/postgrestore/store.go
> +	ctx, cancel := context.WithTimeout(ctx, 1*time.Second)
Хорошая идея, будет хорошо добавить и в другие методы. Значение тайм-аута пока можно вынести в константу уровня пакета

2024-02-16 00:47 UTC, Nikscorp commented on internal/store/postgrestore/store.go
> +				return 0, fmt.Errorf("can't do generate ID: %w", err)
обычно пишут просто что-то вроде generate ID: %w.

Все эти can't / failed to / got error — лишние, тк это и так ошибка

2024-02-16 00:47 UTC, Nikscorp commented on internal/store/postgrestore/store.go
> +  url TEXT NOT NULL
ты используешь url как предикат, почему по нему нет индекса?

2024-02-16 00:47 UTC, Nikscorp commented on internal/store/postgrestore/store.go
> +		if errors.Is(err, sql.ErrNoRows) {
тут гарантий нет, что у тебя два параллельных реквеста не вставят один и тот же url. Стоит добавить unique constraint на url.

И тогда твой можно вообще делать сразу insert с OnConflict и returning https://www.postgresql.org/docs/current/sql-insert.html#SQL-ON-CONFLICT

2024-02-16 19:09 UTC, goshansmails commented on cmd/shortener/main.go
> +			logger.Fatal("can't create postgres store", field, zap.String("error", err.Error()))
там нет return, потому что дальше logger.Fatal выполнение не пойдет

я долго думал как оформить создание Store, чтобы было не много кода, и по логам было понятно что происходит и какой тип стора пытаемся создать. В итоге сделал так. По сути это даже не функция, а кусок кода функции main, который вынесен для удобства

просто паковать всю информацию о происходящем в этой функциии в одну ошибку гораздо сложнее, чем в логи, так как логи структурированные (в отлиции от ошибок)

2024-02-17 17:43 UTC, goshansmails commented on internal/store/postgrestore/store.go
> +				return 0, fmt.Errorf("can't do generate ID: %w", err)
исправил, я правильно понимаю что в самих логах can't/failed допустимы?

2024-02-19 20:16 UTC, Nikscorp commented on cmd/shortener/main.go
> +			logger.Fatal("can't create postgres store", field, zap.String("error", err.Error()))
> там нет return, потому что дальше logger.Fatal выполнение не пойдет

справедливо, мой косяк

2024-02-19 20:16 UTC, Nikscorp commented on internal/store/postgrestore/store.go
> +				return 0, fmt.Errorf("can't do generate ID: %w", err)
конечно

2024-02-19 20:29 UTC, Nikscorp approved these changes
Не все ишью были исправлены как хотелось бы, но окей, работа принята :)

2024-02-19 20:29 UTC, Nikscorp commented on internal/server/shorten_batch.go
> +	respBody, _ := json.Marshal(respData.Items)
вообще ошибки marshal / unmarshal не стоит игнорировать. Кто знает как у тебя изменится структура со временем

2024-02-19 20:29 UTC, Nikscorp commented on internal/store/postgrestore/store.go
> +	ctx, cancel := context.WithTimeout(ctx, 1*time.Second)
тут забыл заиспользовать константу

2024-02-20 19:54 UTC, merged