Do increment #9
goshansmails/shortener pull request #9
Opened 2024-01-23 18:56 UTC by goshansmails

2024-01-30 07:16 UTC, Nikscorp requested changes
Оставил замечания в комментариях к pr

2024-01-30 07:16 UTC, Nikscorp commented on internal/server/interceptors.go
> +		duration := finish.Sub(start)
time.Since

2024-01-30 07:16 UTC, Nikscorp commented on internal/server/interceptors.go
> +		s.logger.Info("request success", fields...)
если во внутреннем хэндлере случится паника — мы ничего не заллогируем. Логировать лучше в defer

2024-01-30 07:16 UTC, Nikscorp commented on internal/server/interceptors.go
> +type gzipReadCloser struct {
gzip и логирующая миддлвара никак не связаны, лучше разнести их по разным подпакетам

2024-01-30 07:16 UTC, Nikscorp commented on internal/server/server.go
> +		h = server.HTTPGzipInterceptor(h)
зачем так? у chi router-а есть метод Use. И никакие циклы тебе не нужны

2024-01-30 07:16 UTC, Nikscorp commented on internal/server/shorten_url.go
> +func (s *Server) ShortenURL2(resp http.ResponseWriter, req *http.Request) {
что за ShortenURL2? Почему не сделать адекватное имя?

2024-01-30 21:27 UTC, goshansmails commented on internal/diskstore/filestore/filestore.go
> +	_, err = s.w.Write(data)
в этой программе такого не может быть: filestore используется только в store, а в store есть мьютекс.

Но получается что у меня есть неявная связь между filestore и store, надо либо объединить filestore и store в один класс, либо добавить мьютекс в filestore

2024-01-30 22:04 UTC, goshansmails commented on cmd/shortener/main.go
> +		logger.Fatal("can't start server", zap.String("error", err.Error()))
run)

2024-01-30 22:10 UTC, goshansmails commented on internal/config/config.go
> +	Address             string
наверное, чтобы доступ к ним был отовсюду, но заменю на структуру

2024-01-30 23:23 UTC, goshansmails commented on internal/server/interceptors.go
> +		duration := finish.Sub(start)
исправил

2024-01-30 23:42 UTC, goshansmails commented on cmd/shortener/main.go
> +func createLogger() *zap.Logger {
исправил

2024-01-31 18:37 UTC, goshansmails commented on internal/server/interceptors.go
> +type gzipReadCloser struct {
сделал 2 пакета: arcive и log

2024-01-31 18:45 UTC, goshansmails commented on internal/diskstore/filestore/filestore.go
> +	_, err = s.w.Write(data)
Решил сохранить Filestore и добавил мьютекс, так как кажется что в целом интерфейс Diskstore удообен

2024-01-31 18:46 UTC, goshansmails commented on internal/server/interceptors.go
> +		s.logger.Info("request success", fields...)
исправил

2024-01-31 19:06 UTC, goshansmails commented on internal/server/shorten_url.go
> +func (s *Server) ShortenURL2(resp http.ResponseWriter, req *http.Request) {
нашел нормальные имена

2024-01-31 21:33 UTC, goshansmails commented on internal/server/server.go
> +		h = server.HTTPGzipInterceptor(h)
исправил

2024-02-01 21:37 UTC, goshansmails commented on internal/server/interceptors.go
> +	size, err := r.ResponseWriter.Write(b)
да, исправил,
у меня это нигде не проявлялось, т.к. нигде не было Write до WriteHeader, т.к. в случае успеха возвращали 201 и 307 (а не 200)

2024-02-05 10:32 UTC, Nikscorp approved these changes
Хорошая работа над ошибками, работа принята

2024-02-05 10:32 UTC, Nikscorp commented on internal/server/shorten_url_test.go
> +func TestShortenURL2(t *testing.T) {
тут тоже нейминг бы поправить

2024-02-05 18:27 UTC, goshansmails commented on internal/server/shorten_url_test.go
> +func TestShortenURL2(t *testing.T) {
исправил

2024-02-05 18:32 UTC, merged